title: Adriel Ferreira Trajano
logo: /assets/img/headshot_circle.png
show_downloads: true
theme: jekyll-theme-minimal

url: "https://adriel1ft.github.io"  

baseurl: "/adriel1ft/example-portfolio"  

languages:
  en:
    title: Adriel Ferreira Trajano (EN)
    description: English version
    permalink: /en/  

  pt-br:
    title: Adriel Ferreira Trajano (PT-BR)
    description: Versão em Português
    permalink: /pt-br/ 